POST http://127.0.0.1:8080/events/collection
Content-Type: application/json
Accept: application/json

[
  {
    "type":"CounterCreated",
    "aggregateId": "00000000-0000-0000-0000-000000000000",
    "counterName": "hello 1"
  },
  {
    "type":"CounterIncremented",
    "aggregateId": "00000000-0000-0000-0000-000000000000",
    "by": "max",
    "withValue": 2
  },
  {
    "type":"CounterIncremented",
    "aggregateId": "00000000-0000-0000-0000-000000000000",
    "by": "max",
    "withValue": 3
  },
  {
    "type":"CounterIncremented",
    "aggregateId": "00000000-0000-0000-0000-000000000000",
    "by": "max"
  },
  {
    "type":"CounterSuspended",
    "aggregateId": "00000000-0000-0000-0000-000000000000",
    "reason": "because!"
  }
]

###
GET http://127.0.0.1:8080/events/00000000-0000-0000-0000-000000000000
Accept: application/json

###
GET http://127.0.0.1:8080/events/00000000-0000-0000-0000-000000000000/collection
Accept: application/json

###
DELETE http://127.0.0.1:8080/events
Accept: application/json

###
POST http://127.0.0.1:8080/events
Content-Type: application/json
Accept: application/json

{
  "aggregateId": "00000000-0000-0000-0000-000000000000",
  "counterName": "hello",
  "type": "CounterCreated"
}

###
GET http://127.0.0.1:8080/events
Content-Type: application/json
Accept: application/json

###
